prep-javascript-variables - Thomas Rittwage
TommyRittwage/prep-0422-code-solutions pull request #10
Opened 2022-04-26 19:26 UTC by TommyRittwage

![Screen Shot 2022-04-26 at 12 21 11 PM](https://user-images.githubusercontent.com/103601090/165376934-d433ce4f-17be-4433-ad29-314c09dce458.png)

2022-04-27 15:45 UTC, thebearingedge requested changes

2022-04-27 15:45 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    console.log('Value of nothing:', nothing);
Hi Tommy, be sure to leave out the quotes for numbers, booleans, and null so that the browser doesn't interpret them as strings.

2022-05-04 00:27 UTC, TommyRittwage commented
![Screen Shot 2022-05-03 at 5 26 02 PM](https://user-images.githubusercontent.com/103601090/166607990-12be22b3-8e31-4115-95cd-07221ccb8488.png)

2022-05-04 16:19 UTC, thebearingedge approved these changes

2022-05-04 16:34 UTC, merged